package main

import "github.com/clementus360/scholia/internal/wiki"

// entityLink ties one corpus entity to one article, and records why.
//
// Method and Confidence are kept because this file is generated by a process
// nobody watches. When a link turns out to be wrong, the difference between
// "matched on a coordinate 40 metres away" and "matched on a name and nothing
// else" is the difference between a fixable bug and a guess that should never
// have shipped. Note is the reader-facing half of the same thing.
type entityLink struct {
	Kind       string `json:"kind"` // person | place | event | group
	EntityID   string `json:"entity_id"`
	ArticleID  string `json:"article_id"`
	Relation   string `json:"relation"` // primary | nearby
	Confidence int    `json:"confidence"`
	Method     string `json:"method"`
	Note       string `json:"note"`
}

// neighbour is one edge out of a resolved article, for readers who want to keep
// going. Labels only: an extract for every neighbour would multiply the file
// several times over to serve a click most readers never make, and the browser
// can fetch one from Wikipedia's CDN when they do.
type neighbour struct {
	ArticleID string `json:"article_id"`
	TargetID  string `json:"target_id"`
	Label     string `json:"label"`
	Relation  string `json:"relation"`
	Rank      int    `json:"rank"`
}

// result is one corpus entity's finished work, and the unit of resumability.
type result struct {
	Kind       string          `json:"kind"`
	EntityID   string          `json:"entity_id"`
	Name       string          `json:"name"`
	Articles   []*wiki.Article `json:"articles"`
	Links      []entityLink    `json:"links"`
	Neighbours []neighbour     `json:"neighbours"`
}

type output struct {
	About      map[string]string `json:"_about"`
	Articles   []*wiki.Article   `json:"articles"`
	Links      []entityLink      `json:"links"`
	Neighbours []neighbour       `json:"neighbours"`
}

// entity is a row the corpus already holds: a person, place, event or group
// that verses point at.
type entity struct {
	Kind       string
	ID         string
	Name       string
	AlsoCalled []string
	// Places only. Zero when the corpus has no fix on the site.
	Latitude  float64
	Longitude float64
	HasCoords bool
	// People only, from person_relations: the corpus's own genealogy, which is
	// what tells King Saul apart from Paul the Apostle.
	Relations map[string][]string
}
